name: Azure Web App Deploy

on:
  push:
    branches:
      - main
      - main2

env:
  ACR_NAME: myacrlab
  IMAGE_NAME: flask-webapp
  WEBAPP_NAME: flask-webapp-702

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        run: |
          docker login $ACR_NAME.azurecr.io \
          -u ${{ secrets.ACR_USERNAME }} \
          -p ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
          -t $ACR_NAME.azurecr.io/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push \
          $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: flask-webapp-702
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: myacrlab.azurecr.io/flask-webapp:latest